import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderHome from "@/components/home/header-home";
import { Toaster } from "@/components/ui/toaster";
import { NextUIProviders } from "@/providers/next-ui-provider";
import NavigationBar from "@/components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <NextUIProviders>
          <div className="flex flex-col">
            <NavigationBar />
            {children}
          </div>
          <Toaster />
        </NextUIProviders>
      </body>
    </html>
  );
}
